language: go
go:
  - 1.12

branches:
  only:
  - master

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  # install all of the dependencies you need here
  # - dep ensure
  - go get golang.org/x/lint/golint
  - go get github.com/haya14busa/goverage

before_script:
  # execute all of the commands which need to be executed
  # before running actual tests
  - PKGS=$(go list ./...)
  - LINT_PKGS=$(go list ./... | grep -Ev 'aws-lambda-go/lambda')

jobs:
  include:
    - stage: test
      script: "./test.sh"
    - stage: build
      script: "./build.sh"
