language: go
go:
- '1.12.1'

branches:
  only:
  - master

before_install:
  # execute all of the commands which need to be executed
  # before installing dependencies
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  # install all of the dependencies you need here

before_script:
  # execute all of the commands which need to be executed
  # before running actual tests
  - go get -u github.com/golang/lint/golint


jobs:
  include:
    - stage: test
      script: "./test.sh"
